// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PromactAsp.Data;

namespace PromactAsp.Migrations
{
    [DbContext(typeof(PromactAspContext))]
    [Migration("20200206124106_Seeddataadded")]
    partial class Seeddataadded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PromactAsp.Models.Message", b =>
                {
                    b.Property<int>("messageid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("iscomment")
                        .HasColumnType("int");

                    b.Property<string>("message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("msglikes")
                        .HasColumnType("int");

                    b.Property<int>("parentid")
                        .HasColumnType("int");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("messageid");

                    b.ToTable("Message");

                    b.HasData(
                        new
                        {
                            messageid = 1,
                            iscomment = 0,
                            message = "I am Ironman",
                            msglikes = 3000,
                            parentid = 0,
                            username = "Ironman"
                        },
                        new
                        {
                            messageid = 2,
                            iscomment = 0,
                            message = "Bring me Thanos",
                            msglikes = 4000,
                            parentid = 0,
                            username = "Thor"
                        },
                        new
                        {
                            messageid = 3,
                            iscomment = 0,
                            message = "Avengers Assemble",
                            msglikes = 2000,
                            parentid = 0,
                            username = "Captain America"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
